### ISSUE TITLE
yarn dev的时候报错

### ISSUE THREAD

**Issue by danzhoua** [sunjunwei11/sunjunwei11-my-vite-vue3-ts-template#1]
![image](https://user-images.githubusercontent.com/15057816/207019829-9e845789-a441-4d82-93e6-a22b1fbf9bdd.png)

**Comment by sunjunwei11** [comment]
git clone后执行pnpm install，然后执行pnpm dev，看下是否还报错？

**Comment by danzhoua** [comment]
![image](https://user-images.githubusercontent.com/15057816/207238655-d0e0532f-44ca-456b-a4d7-753771f8324a.png)

**Comment by danzhoua** [comment]
vue.config.js alias的配置有问题，我换了个写法可以了
